name: jordan_insider
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  intl: ^0.18.1
  flutter_screenutil: ^5.9.0
  flutter_painter: ^1.0.1
  flutter_svg: ^2.0.7
  hexcolor: ^3.0.1
  smooth_page_indicator: ^1.1.0
  simple_star_rating: ^0.0.3
  dio: ^5.4.0
  conditional_builder_null_safety: ^0.0.6
  audioplayers: ^5.2.1
  image_picker: ^1.0.5
  logger: ^2.0.2+1
  motion_toast: ^2.7.10
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  app_bar_with_search_switch: ^1.7.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  camera: ^0.10.5+7
  url_launcher: ^6.1.14
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  flutter_downloader: ^1.11.6
  path: ^1.8.3
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppLogo.png"
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application :
  assets:
    - assets/images/
    - assets/sounds/
    - .env
    - assets/help.docx
  
  # fonts:
  #   - family: AmiriQuran
  #     fonts:
  #       - asset: fonts/AmiriQuran-Regular.ttf
  #   #       style: italic
  #   - family: RobotoCondensed
  #     fonts:
  #       - asset: fonts/RobotoCondensed-Regular.ttf
